POST https://projeto-estudo-nodejs.onrender.com/videos
Content-Type: application/json

{
    "title": "Vídeo node",
    "description": "Esse é o vídeo 1",
    "duration": 180
}

###

GET https://projeto-estudo-nodejs.onrender.com/videos?search=node

###

PUT https://projeto-estudo-nodejs.onrender.com/videos/e142ca84-4b61-412d-94a8-9d4202d3108c
Content-Type: application/json

{
    "title": "Vídeo 2 teste",
    "description": "Esse é o vídeo 1",
    "duration": 180
}

###

DELETE https://projeto-estudo-nodejs.onrender.com/videos/c4b524e3-3dbc-4f52-a6bf-efaf57352544