POST https://projeto-estudo-nodejs.onrender.com/videos 
Content-Type: application/json

{
    "title": "Vídeo node",
    "description": "Esse é o vídeo 1",
    "duration": 180
}

###

GET https://projeto-estudo-nodejs.onrender.com/videos?search=node

###

PUT https://projeto-estudo-nodejs.onrender.com/videos/6555bc46-ffe9-45e4-b47a-28d540cb7f6a
Content-Type: application/json

{
    "title": "Vídeo 2 teste node",
    "description": "Esse é o vídeo 1",
    "duration": 180
}

###

DELETE https://projeto-estudo-nodejs.onrender.com/videos/c4b524e3-3dbc-4f52-a6bf-efaf57352544